### ISSUE TITLE
Query params are not cleared if token already exists

### ISSUE THREAD

**Issue by dchiquit** [girder/girder-oauth-client#7]
The code path that deletes `code` and `state` from the query parameters only runs when the token does not exist in local storage. When the login flow completes, but a token is already saved in local storage, the saved token is used and the query parameters are completely ignored.

The only reasonable way to encounter this behavior is to somehow start two simultaneous login flows, then complete them sequentially. Upon redirecting back to the client, the second login flow will load the token from the first flow and ignore the query parameters, putting the URL string into a slightly dubious state.
It can also happen if a user somehow starts the login flow again while already logged in, but being able to do that probably indicates a bug somewhere else.

**Comment by brianhelba** [comment]
Makes sense. This can probably be fixed alongside #1, since we can be more aggressive about removing query parameters, knowing that it's more selective.
