### ISSUE TITLE
Determine appropriate build settings

### ISSUE THREAD

**Issue by brianhelba** [girder/girder-oauth-client#9]
What ES version should we target during build? Most consumers will not transpile this library, so we want something that should work in all target environments (which will always be a browser, never Node) and will be interpretable by typical bundler tools.

There are two major decision points:
* Import type
  * Ideally, we can ship ES-module imports (rather than CommonJS)
* General language version
  * Perhaps it's a good idea to transpile away extremely new language features

Useful references:
https://www.typescriptlang.org/docs/handbook/compiler-options.html
https://stackoverflow.com/questions/50986494/what-does-the-typescript-lib-option-really-do
https://stackoverflow.com/questions/48378495/recommended-typescript-config-for-node-8

**Comment by brianhelba** [comment]
@zachmullen Can you post the full build error from when you tried to use this package with Vue-CLI? Can you include the Node version of your build machine?

**Comment by zachmullen** [comment]
```Failed to compile.

./node_modules/@girder/oauth-client/dist/resolving-redirect-request-handler.js 21:65
Module parse failed: Unexpected token (21:65)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|             // Based on the implementation of completeAuthorizationRequest, the error is
|             // typically available at this point, but it cannot be structurally guaranteed
>             const errorCode = authorizationRequestResponse.error?.error;
|             const errorDescription = authorizationRequestResponse.error?.errorDescription;
|             // This is an explicit server-provided error, so log it

**Comment by brianhelba** [comment]
@zachmullen Please try upgrading `@girder/oauth-client` to `0.7.0`. That should no longer require using `transpileDependencies` with it.
